export const BaseUrl = `http://127.0.0.1:8000/api/`;

export const LOGIN = "login";
export const showEmployees = "show_employees";
export const showInternalStatistics = "statistics/InternalStatisticsSummary";
export const showExternalStatistics = "statistics/external";
export const registerEmployee = "register-employee";
export const CHECK_SESSION="check-session";
/////
export const show_internal_mails_export = "show_internal_mails_export";
export const show_import_internal_mails = "show_import_internal_mails";
export const ARCHIV = "archive/";
export const INTERNAL = "internal/";
export const MAILS = "mails";
export const TRANSACTION = "transaction/";
export const ARCHIVED_EXPORT = "archived-export";
export const IMPORT = "import/";
export const TRANSACTIONIMPORT = "transaction/import";
export const EXPORT = "export";
export const CREATE_INTERNAL_MAIL="create_internal_mail"
export const FETCHOFFICE="all_paths"
export const SHOW_INTERNAL_MAIL="show_internal_mail_details"
export const Specializations ="specializations/"
export const Show_All="show_all"
export const ADD="add"
export const PROGRAM="program/"
export const ADD_QUESTION_MANUAL="add_question_manual"
export const ADDEXELQUESTIONS ="addExcelQuestions"
export const CANDIDATES="candidates/"
export const PRESENT="present/"
export const ALL="all"
export const SHOW_ALL_IMPORT_REQUSET_EXAM="show_all_import_request_exam"
export const SHOW_ALL_END_REQUSET_EXAM="show_all_end_request_exam"
export const EXAM="exam/"
export const BY="by/"
export const EMPLOYEES="employees/"
    export const Show="show/"
export const PATH="path/"
