export const BaseUrl = `https://0e73798afac3.ngrok-free.app/api/`;

export const LOGIN = "login";
export const showEmployees = "show_employees";
export const showInternalStatistics = "statistics/InternalStatisticsSummary";
export const showExternalStatistics = "statistics/external";
export const registerEmployee = "register-employee";
export const CHECK_SESSION="check-session";
/////
export const show_internal_mails_export = "show_internal_mails_export";
export const show_import_internal_mails = "show_import_internal_mails";
export const ARCHIV = "archive/";
export const INTERNAL = "internal/";
export const MAILS = "mails";
export const TRANSACTION = "transaction/";
export const ARCHIVED_EXPORT = "archived-export";
export const IMPORT = "import/";
export const TRANSACTIONIMPORT = "transaction/import";
export const EXPORT = "export";
export const CREATE_INTERNAL_MAIL="create_internal_mail"
export const FETCHOFFICE="all_paths"
export const SHOW_INTERNAL_MAIL="show_internal_mail_details"
export const Specializations ="specializations/"
export const Show_All="show_all"
export const ADD="add"
export const PROGRAM="program/"
export const ADD_QUESTION_MANUAL="add_question_manual"
export const ADDEXELQUESTIONS ="addExcelQuestions"
export const CANDIDATES="candidates/"
export const PRESENT="present/"
export const ALL="all"
export const SHOW_ALL_IMPORT_REQUSET_EXAM="show_all_import_request_exam"
export const SHOW_ALL_END_REQUSET_EXAM="show_all_end_request_exam"
export const EXAM="exam/"
export const BY="by/"
export const EMPLOYEES="employees/"
    export const Show="show/"
export const PATH="path/"
export const SHOW_FORM_CONTENT ="show_form_content_exam"
export const EDIT_FORM_CONTENT_EXAM ="edit_form_content_exam_status"
export const WORKING_HOURS ="working-hours"
export const PATHS="paths/"
export const ACHIEVEMENT="achievement"
export const STATISTICS="statistics/"
export const FORM ="form/"
export const SHOW_ALL ="show_all"
export const WEEKLY_DONE ="weekly-done"
export const WEEKLY_HOURS_SHOW ="working-hours/show"
export const WEEKLY_HOURS ="working-hours"
export const  WEEKLY ="weekly/path/"
export const WEEKLYPATH ="weekly/path/"
export const  EDIT_STATUS_MAIL="edit_status_internal_mails"
export const ANNOUNCEMENT ="announcement/"
export const UPDATE_STATUS ="update-status/"
export const REVIEW ="review/"
export const RECEPIET_IMAGE ="receipt_image/"
export const UNDER="under-review/"
export const RECEPIET_STATUS ="receipt_status/"
export const STATUS ="status/"
export const ALL_ROLL ="all_roles"
export const CONTENT ="content/"
export const EDIT_EMPLOYEE_INFORMATION ="edit_employee_information"
export const SEARCH ="search/"
export const EMPLOYEE ="Employee"
export const CONVERT_STATUS ="ConverStatus/"
export const TOOGLE_STATUS = "toggle-status/"
export const eMPLOYEE ="employee"
export const Specialization ="Specialization/"
export const NAME ="Name"
export const EXAME ="Exam/"
export const REQUEST ="request"
export const Announcements ="Announcements"
export const UPLOUD_WORD ="upload-word"
export const ARCHIVED ="archived"
export const TRANSACTIONN = "transaction";

